### ISSUE TITLE
IndexError: index out of range in STDF.records_from_file

### ISSUE THREAD

**Issue by Freeman266** [Semi-ATE/STDF#55]
### Tasks/Steps/Elements

Need your help on this index out of range. Below is the error

Traceback (most recent call last):

  File "C:\Users\user\stdf\stdrreader.py", line 10, in <module>
    for REC in STDF.records_from_file("stdf.std"):

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\utils.py", line 810, in __next__
    return create_record_object(self.version, self.endian, (REC_TYP, REC_SUB), header+footer)

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\utils.py", line 861, in create_record_object
    retval = create_record(Version, Endian, REC_ID, REC)

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\utils.py", line 885, in create_record
    retval = GDR(Version, Endian, REC)

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\GDR.py", line 35, in __init__
    self._default_init(endian, record)

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\STDR.py", line 265, in _default_init
    self._unpack(record)

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\STDR.py", line 1798, in _unpack
    self._unpack_item(items[index])

  File "C:\Users\user\Anaconda3\lib\site-packages\semi_ate_stdf-0.0.0-py3.8.egg\Semi_ATE\STDF\STDR.py", line 1508, in _unpack_item
    code = self.buffer[0]

IndexError: index out of range

### Versions checklist

* Spyder version: >= 4.2.5
* Python version: 3.8.8
* Qt version: all
* PyQt version: all
* Operating System name/version:
  - client : Windows

**Comment by csraghu** [comment]
I ran into the same issue and looks like the problem is due to the buffer being empty. By just breaking out of the loop when the buffer is empty fixes the error. Probably that might not be the right solution (though it works). Will be glad if this issue can be resolved. 

Thanks

**Comment by dmitry5999** [comment]
Same issue happen to me as well. Looks like treating GDR record is buggy. Sometimes buffer parsing ends up to be empty.
I fixed it as described before. Only note yo should not break the loop, but continue. Writing GDR record back to STDF is buggy as well. Failing the check of record length.

**Comment by aulinof** [comment]
Hello to everyone, based on your strategy to solve the problem, maybe I have found a solution for which I don't know if necessary to submit it to any approval cycle. I have modified the the code directly in the file STDR.py in the library.  In particular I have added in the old one row 1508 the code "if self.buffer[0] else 'empty'" and also added the new two rows 1509 e 1510. Bye Thanks

1507                        for i in range(K):
1508                           code = self.buffer[0] if self.buffer[0] else 'empty'
1509                            if code == 'empty':
1510                               break 
1511                            if code == 0:
